export const experienceItems = [
  {
    duration: "Jan 2023 — Mar 2024",
    durationLabel: "Jan 2023 — Mar 2024",
    company: "Zillow",
    projectName: "Zillow",
    jobTitle: "Senior Full-Stack Developer",
    href: "https://www.zillow.com/",
    skills: [
      "Javascript",
      "Typescript",
      "React",
      "Next.js",
      "Material UI",
      "Apexcharts",
      "Contentful",
      "Formik",
      "Calendar",
      "React native",
      "Node",
      "Express",
      "PostgreSQL",
      "Docker",
      "Circle CI",
    ],
  },
  {
    duration: "May 2022 — Dec 2022",
    durationLabel: "May to December 2022",
    company: "Wreno",
    projectName: "Wreno",
    jobTitle: "Senior Front-End Developer",
    href: "https://wreno.io/",
    skills: [
      "Typescript",
      "React",
      "Next.js",
      "React hook form",
      "Firebase",
      "Pubnub",
      "Calendar",
      "Yup",
      "Vercel",
    ],
  },
  {
    duration: "Feb 2020 — May 2022",
    durationLabel: "Feb 2020 to May 2022",
    company: "Campuswire",
    projectName: "Campuswire",
    jobTitle: "Senior Web & Mobile Developer",
    href: "https://campuswire.com/",
    skills: [
      "React",
      "React Query",
      "Three.js",
      "Video.js",
      "Prosemirror",
      "Markdown",
      "Highlight.js",
      "Chart.js",
      "Agora RTC",
      "Socket.io",
      "Stripe",
      "React native",
    ],
  },
  {
    duration: "May 2017 — Jan 2020",
    durationLabel: "May 2017 to Jan 2020",
    company: "Sivo",
    projectName: "Sivo",
    jobTitle: "Senior Frontend Engineer",
    href: "https://app.sivo.com/",
    skills: [
      "React",
      "GraphQL",
      "Amazon Cognito",
      "Persona",
      "Recharts",
      "Uniforms",
      "Node",
      "Express",
      "AWS SDK",
      "Socket.io",
      "Prisma",
      "PostgreSQL",
      "Readme io",
    ],
  },
  {
    duration: "Sep 2014 — Jan 2017",
    durationLabel: "Sep 2014 to Jan 2017",
    company: "Brandy Melville",
    projectName: "Brandy Melville",
    jobTitle: "Frontend Web Developer ",
    href: "https://us.brandymelville.com/",
    skills: ["Scandiweb", "React", "React Query", "HTML", "CSS", "Magento"],
  },
];
